# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

variables:
  - group: demo-kv

stages:
  - stage: TerraformValidate
    jobs:
      - job: TerraformValidateJob
        continueOnError: false
        steps:
        - task: PublishPipelineArtifact@1
          displayName: Publish Artifacts
          inputs:
            targetPath: '$(System.DefaultWorkingDirectory)/terraform'
            artifact: 'terraform-manifest-out'
            publishLocation: pipeline
        - task: ms-devlabs.custom-terraform-tasks.custom-terraform-installer-task.TerraformInstaller@0
          displayName: Terraform Install
          inputs:
            terraformVersion: '0.13.5'
        - task: Bash@3
          displayName: Verify Terraform version
          inputs:
            targetType: 'inline'
            script: 'echo `terraform version`'
        - task: Bash@3
          displayName: Terraform Init
          inputs:
            workingDirectory: '$(System.DefaultWorkingDirectory)/terraform'
            targetType: 'inline'
            script: terraform init \
                      -backend-config="storage_account_name=deimos01storage" \
                      -backend-config="container_name=tfstatefiles" \
                      -backend-config="key=terraform.tfstate" \
                      -backend-config="access_key=$TF_STATE_ACCESS_KEY"
            env:
              TF_STATE_ACCESS_KEY:  $(kv-str-access-key)    
        # - task: TerraformCLI@0
        #   displayName: Terraform Init
        #   inputs:
        #     command: 'init'
        #     workingDirectory: '$(System.DefaultWorkingDirectory)/terraform'
        #     backendType: 'azurerm'
        #     backendAzureRmResourceGroupName: 'storage-rg'
        #     backendAzureRmStorageAccountName: 'deimos01storage'
        #     backendAzureRmContainerName: 'tfstatefiles'
        #     backendAzureRmKey: 'devops-terraform.tfstate'
        #     allowTelemetryCollection: false
        # - task: TerraformCLI@0
        #   displayName: Terraform Validate
        #   inputs:
        #     command: 'validate'
        #     workingDirectory: '$(System.DefaultWorkingDirectory)/terraform'
        #     allowTelemetryCollection: false
